apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-marketplace

resources:
  # namespace already exists from API deployment
  # - namespace.yaml
  - web-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"
  environment: edge

images:
  - name: agent-marketplace-web
    newTag: latest
