apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-marketplace

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - web-deployment.yaml
  - database.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/version: "1.0.0"

images:
  - name: agent-marketplace-web
    newTag: latest
